<?php

// This file is generated by Composer

require_once __DIR__ . '/vendor/autoload.php';

$client = new \Harmony\SDK\Client();
$client->authenticate('OGY0NDVhOTNhOWU1NjQ0YWViOTFhMjhjZWQzNTZhNWU5Y2E2ZmMwYmFkMjQ1YmFkNTg3MTIyOWVhMTNlODgzNQ', null,
    \Harmony\SDK\Client::AUTH_HTTP_TOKEN);
/** @var \Harmony\SDK\Receiver\Users $users */
$users = $client->getReceiver(\Harmony\SDK\Client::RECEIVER_USERS);
var_dump($users->getUser());